"""add score database

Revision ID: 866adef73cf3
Revises: 5ff8bf1dcf07
Create Date: 2022-12-06 11:32:30.924783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866adef73cf3'
down_revision = '5ff8bf1dcf07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfect', sa.Integer(), nullable=True),
    sa.Column('great', sa.Integer(), nullable=True),
    sa.Column('good', sa.Integer(), nullable=True),
    sa.Column('bad', sa.Integer(), nullable=True),
    sa.Column('miss', sa.Integer(), nullable=True),
    sa.Column('totalScore', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    # ### end Alembic commands ###
