"""add event name

Revision ID: bf039588e641
Revises: b3b881b91e75
Create Date: 2022-12-08 14:12:44.313216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf039588e641'
down_revision = 'b3b881b91e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('finalScore', sa.Float(), nullable=True))
        batch_op.drop_column('totalScore')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalScore', sa.INTEGER(), nullable=True))
        batch_op.drop_column('finalScore')
        batch_op.drop_column('event')

    # ### end Alembic commands ###
